name: Daily Commit Push

on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 PM UTC
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  push-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures all commits are available

      - name: Configure Git
        run: |
          git config --global user.name "YourGitHubUsername"
          git config --global user.email "your-email@example.com"

      - name: Push Next Commit
        run: |
          # Check if there are commits to push
          if [ "$(git log origin/main..HEAD --oneline | wc -l)" -gt "0" ]; then
            git push origin main
          else
            echo "No new commits to push today."
          fi
